prepare Bcp for changing some LPs into TM storage places. Serial version works, currently debugging parallel version.

diff --git a/Bcp/configure b/Bcp/configure
--- a/Bcp/configure
+++ b/Bcp/configure
@@ -1105,9 +1105,8 @@ Optional Packages:
                           both]
   --with-tags[=TAGS]
                           include additional configurations [automatic]
-  --with-mpi-incdir specify the directory with the header files for library
-                          Mpi
-  --with-mpi-lib specify the flags to link with the library Mpi
+  --with-mpi-incdir specify the header file directory for library Mpi
+  --with-mpi-lib specify the flags used to link with the library Mpi
 
 Some influential environment variables:
   CDEFS       Additional -D flags to be used when compiling C code.
@@ -1752,7 +1751,10 @@ fi
 # Check whether --with-bcp-verbosity or --without-bcp-verbosity was given.
 if test "${with_bcp_verbosity+set}" = set; then
   withval="$with_bcp_verbosity"
-  coin_bcp_verbosity=$withval
+  if test "$withval" = yes; then
+                withval=1
+              fi
+              coin_bcp_verbosity=$withval
 else
   coin_bcp_verbosity=0
 fi;
@@ -1766,7 +1768,10 @@ _ACEOF
 # Check whether --with-bcp-checklevel or --without-bcp-checklevel was given.
 if test "${with_bcp_checklevel+set}" = set; then
   withval="$with_bcp_checklevel"
-  coin_bcp_checklevel=$withval
+  if test "$withval" = yes; then
+                withval=1
+              fi
+              coin_bcp_checklevel=$withval
 else
   coin_bcp_checklevel=0
 fi;
@@ -5638,7 +5643,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 5641 "configure"' > conftest.$ac_ext
+  echo '#line 5646 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6772,7 +6777,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:6775:" \
+echo "$as_me:6780:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7839,11 +7844,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7842: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7847: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7846: \$? = $ac_status" >&5
+   echo "$as_me:7851: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8107,11 +8112,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8110: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8115: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8114: \$? = $ac_status" >&5
+   echo "$as_me:8119: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8211,11 +8216,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8214: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8219: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:8218: \$? = $ac_status" >&5
+   echo "$as_me:8223: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -10556,7 +10561,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10559 "configure"
+#line 10564 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10656,7 +10661,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10659 "configure"
+#line 10664 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13000,11 +13005,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13003: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13008: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13007: \$? = $ac_status" >&5
+   echo "$as_me:13012: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13104,11 +13109,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13107: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13112: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13111: \$? = $ac_status" >&5
+   echo "$as_me:13116: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14674,11 +14679,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14677: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14682: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14681: \$? = $ac_status" >&5
+   echo "$as_me:14686: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14778,11 +14783,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14781: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14786: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14785: \$? = $ac_status" >&5
+   echo "$as_me:14790: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16985,11 +16990,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16988: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16993: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16992: \$? = $ac_status" >&5
+   echo "$as_me:16997: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17253,11 +17258,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17256: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17261: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:17260: \$? = $ac_status" >&5
+   echo "$as_me:17265: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -17357,11 +17362,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:17360: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:17365: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:17364: \$? = $ac_status" >&5
+   echo "$as_me:17369: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20095,7 +20100,8 @@ echo "$as_me: Applying patches to libtool for cl compiler" >&6;}
   	    -e 's%$AR x \\$f_ex_an_ar_oldlib%bla=\\`lib -nologo -list \\$f_ex_an_ar_oldlib | xargs echo\\`; echo \\$bla; for i in \\$bla; do lib -nologo -extract:\\$i \\$f_ex_an_ar_oldlib; done%' \
 	    -e 's/$AR t/lib -nologo -list/' \
 	    -e 's%f_ex_an_ar_oldlib="\($?*1*\)"%f_ex_an_ar_oldlib='\`"$CYGPATH_W"' \1`%' \
-	    -e  's%^archive_cmds=.*%archive_cmds="\\$CC -o \\$lib \\$libobjs \\$compiler_flags \\\\\\`echo \\\\\\"\\$deplibs\\\\\\" | \\$SED -e '"\'"'s/ -lc\\$//'"\'"'\\\\\\` -link -dll~linknames="%' \
+	    -e 's%^archive_cmds=.*%archive_cmds="\\$CC -o \\$lib \\$libobjs \\$compiler_flags \\\\\\`echo \\\\\\"\\$deplibs\\\\\\" | \\$SED -e '"\'"'s/ -lc\\$//'"\'"'\\\\\\` -link -dll~linknames="%' \
+	    -e 's%old_archive_cmds="lib -OUT:\\$oldlib\\$oldobjs\\$old_deplibs"%old_archive_cmds="if test -r \\$oldlib; then bla=\\"\\$oldlib\\"; else bla=; fi; lib -OUT:\\$oldlib \\\\\\$bla\\$oldobjs\\$old_deplibs"%' \
         libtool > conftest.bla
 
         mv conftest.bla libtool
@@ -20113,6 +20119,16 @@ echo "$as_me: Applying patches to libtool for GNU compiler" >&6;}
         chmod 755 libtool
         ;;
     esac
+    ;;
+    *-darwin*)
+      { echo "$as_me:$LINENO: Applying patches to libtool for Darwin" >&5
+echo "$as_me: Applying patches to libtool for Darwin" >&6;}
+      sed -e 's/verstring="${wl}-compatibility_version ${wl}$minor_current ${wl}-current_version ${wl}$minor_current.$revision"/verstring="-compatibility_version $minor_current -current_version $minor_current.$revision"/' \
+      libtool > conftest.bla
+
+      mv conftest.bla libtool
+      chmod 755 libtool
+      ;;
   esac
 # This fi matches the commented `if test "x$LIBTOOL" = x;' up at the head of
 # the macro. -- lh, 061214 --
@@ -20566,25 +20582,30 @@ echo "${ECHO_T}$coin_has_osi" >&6
 #############################################################################
 
 
-echo "$as_me:$LINENO: checking if user provides library for Mpi" >&5
+  echo "$as_me:$LINENO: checking if user provides library for Mpi" >&5
 echo $ECHO_N "checking if user provides library for Mpi... $ECHO_C" >&6
 
 # Check for header file directory
+
 
 # Check whether --with-mpi-incdir or --without-mpi-incdir was given.
 if test "${with_mpi_incdir+set}" = set; then
   withval="$with_mpi_incdir"
   MPIINCDIR=`cd $withval; pwd`
 fi;
+
 # Check for library directory
+
 
 # Check whether --with-mpi-lib or --without-mpi-lib was given.
 if test "${with_mpi_lib+set}" = set; then
   withval="$with_mpi_lib"
   MPILIB=$withval
 fi;
+
 # Switch to disable library check if requested
-# Check whether --enable-mpi-libcheck or --disable-mpi-libcheck was given.
+
+  # Check whether --enable-mpi-libcheck or --disable-mpi-libcheck was given.
 if test "${enable_mpi_libcheck+set}" = set; then
   enableval="$enable_mpi_libcheck"
   mpi_libcheck=$enableval
@@ -20592,23 +20613,32 @@ else
   mpi_libcheck=yes
 fi;
 
-if test x"$MPIINCDIR" != x || test x"$MPILIB" != x; then
-  coin_has_mpi=true
-else
-  coin_has_mpi=false
-fi
+# At this point, if we're going to use the library, both LBRYINCDIR and
+# LBRYLIB must be defined and not empty.
 
-if test $coin_has_mpi = true; then
-# Check either both arguments or none are given
-  if test x"$MPIINCDIR" = x || test x"$MPILIB" = x; then
-    { { echo "$as_me:$LINENO: error: You need to specify both --with-mpi-incdir and --with-mpi-lib if you want to use library Mpi" >&5
-echo "$as_me: error: You need to specify both --with-mpi-incdir and --with-mpi-lib if you want to use library Mpi" >&2;}
+  if test x"$MPIINCDIR" != x || test x"$MPILIB" != x; then
+    if test x"$MPIINCDIR" = x || test x"$MPILIB" = x; then
+      { { echo "$as_me:$LINENO: error: You need to specify both an include directory and link flags to use library Mpi. Use --with-mpi-incdir of environment variable $MPIINCDIR to specify the include directory. Use --with-mpi-lib or environment variable $MPILIB to specify link flags." >&5
+echo "$as_me: error: You need to specify both an include directory and link flags to use library Mpi. Use --with-mpi-incdir of environment variable $MPIINCDIR to specify the include directory. Use --with-mpi-lib or environment variable $MPILIB to specify link flags." >&2;}
    { (exit 1); exit 1; }; }
-  fi
-  echo "$as_me:$LINENO: result: yes" >&5
+    fi
+    coin_has_mpi=true
+    echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-  # Check if the given header file is there
-  as_ac_File=`echo "ac_cv_file_$MPIINCDIR/mpi.h" | $as_tr_sh`
+  else
+    coin_has_mpi=false
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  fi
+
+# If we have instructions for use, consider header and link checks.
+
+  if test $coin_has_mpi = true; then
+
+# If argument 3 (file) is given, check for the file. Typically this will be a
+# header file, but that's not assumed.
+
+    as_ac_File=`echo "ac_cv_file_$MPIINCDIR/mpi.h" | $as_tr_sh`
 echo "$as_me:$LINENO: checking for $MPIINCDIR/mpi.h" >&5
 echo $ECHO_N "checking for $MPIINCDIR/mpi.h... $ECHO_C" >&6
 if eval "test \"\${$as_ac_File+set}\" = set"; then
@@ -20635,32 +20665,37 @@ echo "$as_me: error: Cannot find file mpi.h in $MPIINCDIR" >&2;}
 fi
 
 
-  # Check if the symbol is provided in the library
-  # ToDo: FOR NOW WE ASSUME THAT WE ARE USING THE C++ COMPILER
-  if test x"$mpi_libcheck" != xno; then
-                    coin_save_LIBS="$LIBS"
-                    LIBS="$MPILIB $ADDLIBS"
-		    echo "$as_me:$LINENO: checking whether symbol MPI_Irecv is available with MPI" >&5
-echo $ECHO_N "checking whether symbol MPI_Irecv is available with MPI... $ECHO_C" >&6
-                    ac_ext=c
+# Now see if we can link the function. There are arguments for and against
+# assuming argument 3 is a header file declaring the function. A correct
+# function declaration is the main argument in favour. Having to cope with
+# possible dependencies or other oddities are the main arguments against.
+# Force the use of C as the best single choice amongst C++, C, and Fortran.
+# Obviously, this has limits.
+
+    if test x"$mpi_libcheck" != xno; then
+	   coin_save_LIBS="$LIBS"
+	   LIBS="$MPILIB $ADDLIBS"
+	   coin_MPI_link=no
+	   ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-# ToDo find out what to do about extern "C"
-#                    AC_TRY_LINK([extern "C" {void MPI_Irecv();}],[MPI_Irecv()],
-                    cat >conftest.$ac_ext <<_ACEOF
+	   for fnm in MPI_Irecv ; do
+	     echo "$as_me:$LINENO: checking whether symbol $fnm is available with MPI" >&5
+echo $ECHO_N "checking whether symbol $fnm is available with MPI... $ECHO_C" >&6
+	     cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-void MPI_Irecv();
+
 int
 main ()
 {
-MPI_Irecv()
+$fnm()
   ;
   return 0;
 }
@@ -20689,37 +20724,48 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   (exit $ac_status); }; }; then
   echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
+		  coin_MPI_link=yes
+		  break
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
 echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
-                                 { { echo "$as_me:$LINENO: error: Cannot find symbol MPI_Irecv with MPI" >&5
-echo "$as_me: error: Cannot find symbol MPI_Irecv with MPI" >&2;}
-   { (exit 1); exit 1; }; }
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-                    ac_ext=c
+	   done
+	   ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
-                    LIBS="$coin_save_LIBS"
-                  fi
+	   if test x"$coin_MPI_link" = xyes ; then
+	     LIBS="$coin_save_LIBS"
+	   else
+	     { { echo "$as_me:$LINENO: error: Cannot find symbol(s) MPI_Irecv with MPI" >&5
+echo "$as_me: error: Cannot find symbol(s) MPI_Irecv with MPI" >&2;}
+   { (exit 1); exit 1; }; }
+	   fi
+	 fi
 
-  ADDLIBS="$MPILIB $ADDLIBS"
+
+# If we make it this far, we've verified the file and linked the function. Add
+# the necessary link flags to ADDLIBS and define the preprocessor symbol
+# COIN_HAS_LBRY.
+
+    ADDLIBS="$MPILIB $ADDLIBS"
 
 cat >>confdefs.h <<\_ACEOF
 #define COIN_HAS_MPI 1
 _ACEOF
 
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
+  fi
+
+# Arrange for configure to substitute LBRYINCDIR and LBRYLIB and create the
+# automake conditional. These actions must occur unconditionally.
 
 
 
