run_autotools

diff --git a/Bcp/configure b/Bcp/configure
--- a/Bcp/configure
+++ b/Bcp/configure
@@ -1075,6 +1075,7 @@ Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-debug          compile all projects with debug options tests
+  --enable-debug-bcp compile this project (Bcp) with debug options
   --enable-static[=PKGS]
                           build static libraries [default=no]
   --disable-dependency-tracking  speeds up one-time build
@@ -1092,6 +1093,8 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-bcp-verbosity specify the debug verbosity level for project Bcp
+  --with-bcp-checklevel specify the sanity check level for project Bcp
   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
   --with-pic              try to use only PIC/non-PIC objects [default=use
                           both]
@@ -1712,7 +1715,25 @@ else
   coin_debug_compile=false
 fi;
 
- # m4_ifvaln([],
+# Check whether --enable-debug-bcp or --disable-debug-bcp was given.
+if test "${enable_debug_bcp+set}" = set; then
+  enableval="$enable_debug_bcp"
+  case "${enableval}" in
+    yes) coin_debug_compile=true
+         enable_shared=no
+         ;;
+    no)  coin_debug_compile=false
+         ;;
+    *) { { echo "$as_me:$LINENO: error: bad value ${enableval} for --enable-debug-bcp" >&5
+echo "$as_me: error: bad value ${enableval} for --enable-debug-bcp" >&2;}
+   { (exit 1); exit 1; }; }
+         ;;
+ esac
+else
+  :
+fi;
+
+ # m4_ifvaln([Bcp],
 
 if test $coin_debug_compile = true; then
   echo "$as_me:$LINENO: result: yes" >&5
@@ -1722,7 +1743,40 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
- # m4_ifvaln([],
+
+# Check whether --with-bcp-verbosity or --without-bcp-verbosity was given.
+if test "${with_bcp_verbosity+set}" = set; then
+  withval="$with_bcp_verbosity"
+  coin_bcp_verbosity=$withval
+else
+  coin_bcp_verbosity=0
+fi;
+
+cat >>confdefs.h <<_ACEOF
+#define COIN_BCP_VERBOSITY $coin_bcp_verbosity
+_ACEOF
+
+
+
+# Check whether --with-bcp-checklevel or --without-bcp-checklevel was given.
+if test "${with_bcp_checklevel+set}" = set; then
+  withval="$with_bcp_checklevel"
+  coin_bcp_checklevel=$withval
+else
+  coin_bcp_checklevel=0
+fi;
+
+cat >>confdefs.h <<_ACEOF
+#define COIN_BCP_CHECKLEVEL $coin_bcp_checklevel
+_ACEOF
+
+
+# We use the following variable to have a string with the upper case
+# version of the project name
+COIN_PRJCT=BCP
+
+
+ # m4_ifvaln([Bcp],
 
 
 
@@ -4697,7 +4751,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4700 "configure"' > conftest.$ac_ext
+  echo '#line 4754 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5831,7 +5885,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5834:" \
+echo "$as_me:5888:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6898,11 +6952,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6901: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6955: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6905: \$? = $ac_status" >&5
+   echo "$as_me:6959: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7166,11 +7220,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7169: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7223: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7173: \$? = $ac_status" >&5
+   echo "$as_me:7227: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7270,11 +7324,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7273: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7327: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7277: \$? = $ac_status" >&5
+   echo "$as_me:7331: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9615,7 +9669,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9618 "configure"
+#line 9672 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9715,7 +9769,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9718 "configure"
+#line 9772 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12059,11 +12113,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12062: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12116: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12066: \$? = $ac_status" >&5
+   echo "$as_me:12120: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12163,11 +12217,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12166: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12220: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12170: \$? = $ac_status" >&5
+   echo "$as_me:12224: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13733,11 +13787,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13736: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13790: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13740: \$? = $ac_status" >&5
+   echo "$as_me:13794: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13837,11 +13891,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13840: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13894: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13844: \$? = $ac_status" >&5
+   echo "$as_me:13898: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16044,11 +16098,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16047: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16101: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16051: \$? = $ac_status" >&5
+   echo "$as_me:16105: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16312,11 +16366,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16315: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16369: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16319: \$? = $ac_status" >&5
+   echo "$as_me:16373: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16416,11 +16470,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16419: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16473: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16423: \$? = $ac_status" >&5
+   echo "$as_me:16477: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20930,6 +20984,48 @@ fi
 fi
 
 
+if test $coin_vpath_config = yes; then
+
+if test examples/MaxCut = . ; then
+	updir=.
+else
+	t=`echo examples/MaxCut | sed -e 's=/\./=/=g' -e 's=^\./==' -e 's=/\.$==' -e 's=[^/]*=..=g'`
+	if test $t = "" ; then
+		t=.
+	fi
+	updir=$t
+fi
+
+	if test -e $srcdir/examples/MaxCut/examplefiles.txt ; then
+		echo Copying example examples/MaxCut ...
+		fromdir=$updir/$srcdir/`dirname examples/MaxCut/examplefiles.txt`
+		mkdir -p examples/MaxCut
+		cd examples/MaxCut
+		for f in `cat $updir/$srcdir/examples/MaxCut/examplefiles.txt` ; do
+			if test ! -e $f ; then
+		   		fdir=`dirname $f`
+				mkdir -p $fdir
+
+if test $fdir = . ; then
+	uppath=.
+else
+	t=`echo $fdir | sed -e 's=/\./=/=g' -e 's=^\./==' -e 's=/\.$==' -e 's=[^/]*=..=g'`
+	if test $t = "" ; then
+		t=.
+	fi
+	uppath=$t
+fi
+
+				cd $fdir
+				cp -p $uppath/$fromdir/$f `basename $f`
+				cd $uppath
+			fi
+		done
+		cd $updir
+	fi
+fi
+
+
 
 if test $coin_vpath_config = yes; then
 
@@ -21076,7 +21172,7 @@ fi
 
 # Here list all the files that configure should create (except for the
 # configuration header file)
-                                                                                ac_config_files="$ac_config_files Makefile src/Makefile test/BAC/Makefile examples/BAC/Makefile examples/MCF-1/Makefile examples/MCF-2/Makefile examples/MCF-3/Makefile bcp_addlibs.txt"
+                                                                                          ac_config_files="$ac_config_files Makefile src/Makefile test/BAC/Makefile examples/BAC/Makefile examples/MCF-1/Makefile examples/MCF-2/Makefile examples/MCF-3/Makefile examples/MaxCut/Makefile bcp_addlibs.txt"
 
 
 # Here put the location and name of the configuration header file
@@ -21735,6 +21831,7 @@ do
   "examples/MCF-1/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/MCF-1/Makefile" ;;
   "examples/MCF-2/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/MCF-2/Makefile" ;;
   "examples/MCF-3/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/MCF-3/Makefile" ;;
+  "examples/MaxCut/Makefile" ) CONFIG_FILES="$CONFIG_FILES examples/MaxCut/Makefile" ;;
   "bcp_addlibs.txt" ) CONFIG_FILES="$CONFIG_FILES bcp_addlibs.txt" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   "inc/config_bcp.h" ) CONFIG_HEADERS="$CONFIG_HEADERS inc/config_bcp.h" ;;
